package io.legado.app.constant

@Suppress("ConstPropertyName")
object PreferKey {
    const val language = "language"
    const val fontScale = "fontScale"
    const val themeMode = "themeMode"
    const val userAgent = "userAgent"
    const val customHosts = "customHosts"
    const val videoSetting = "videoSetting"
    const val editTheme = "editTheme"
    const val publicWebRelayEnabled = "publicWebRelayEnabled"
    const val publicWebRelayWorkerUrl = "publicWebRelayWorkerUrl"
    const val publicWebRelayDeviceName = "publicWebRelayDeviceName"
    const val publicWebRelayDeviceId = "publicWebRelayDeviceId"
    const val publicWebRelayDeviceHandle = "publicWebRelayDeviceHandle"
    const val publicWebRelayPairedWorkerUrl = "publicWebRelayPairedWorkerUrl"
    const val publicWebRelayPermanentShare = "publicWebRelayPermanentShare"
    const val publicWebRelayShareProgressSync = "publicWebRelayShareProgressSync"
    const val editThemeDark = "editThemeDark"
    const val editTemeAuto = "editTemeAuto"
    const val showUnread = "showUnread"
    const val showBookshelfReadProgress = "showBookshelfReadProgress"
    const val showBooknameLayout = "showBooknameLayout"
    const val bookshelfMargin = "bookshelfMargin"
    const val bookGroupStyle = "bookGroupStyle"
    const val useDefaultCover = "useDefaultCover"
    const val loadCoverOnlyWifi = "loadCoverOnlyWifi"
    const val coverShowName = "coverShowName"
    const val coverShowAuthor = "coverShowAuthor"
    const val coverShowNameN = "coverShowNameN"
    const val coverShowAuthorN = "coverShowAuthorN"
    const val remoteServerId = "remoteServerId"
    const val hideStatusBar = "hideStatusBar"
    const val clickActionTL = "clickActionTopLeft"
    const val clickActionTC = "clickActionTopCenter"
    const val clickActionTR = "clickActionTopRight"
    const val clickActionML = "clickActionMiddleLeft"
    const val clickActionMC = "clickActionMiddleCenter"
    const val clickActionMR = "clickActionMiddleRight"
    const val clickActionBL = "clickActionBottomLeft"
    const val clickActionBC = "clickActionBottomCenter"
    const val clickActionBR = "clickActionBottomRight"
    const val hideNavigationBar = "hideNavigationBar"
    const val precisionSearch = "precisionSearch"
    const val readAloudByPage = "readAloudByPage"
    const val ttsEngine = "appTtsEngine"
    const val ttsFollowSys = "ttsFollowSys"
    const val ttsSpeechRate = "ttsSpeechRate"
    const val ttsEngineParamsJson = "ttsEngineParamsJson"
    const val ttsCastingActiveId = "ttsCastingActiveId"
    const val ttsCastingBookOverridePrefix = "ttsCastingBookOverride_"
    const val prevKeys = "prevKeyCodes"
    const val nextKeys = "nextKeyCodes"
    const val showDiscovery = "showDiscovery"
    const val enableReview = "enableReview"
    const val mergeDiscoveryRss = "mergeDiscoveryRss"
    const val showReadRecord = "showReadRecord"
    const val mainBottomNavItems = "mainBottomNavItems"
    const val showRss = "showRss"
    const val bookshelfLayout = "bookshelfLayout"
    const val bookshelfSort = "bookshelfSort"
    const val bookshelfShowBooknameMigrated = "bookshelfShowBooknameMigrated"
    const val bookExportFileName = "bookExportFileName"
    const val bookImportFileName = "bookImportFileName"
    const val episodeExportFileName = "episodeExportFileName"
    const val recordLog = "recordLog"
    const val recordNetworkLog = "recordNetworkLog"
    const val bookSourceFileSandbox = "bookSourceFileSandbox"   // P0-S1 书源文件沙箱开关
    const val blockSourceDialogs = "blockSourceDialogs"         // P0-S3 书源弹窗拦截开关
    const val bookSourceCacheScoped = "bookSourceCacheScoped"       // P0-S2 脚本缓存按源隔离开关
    const val bookSourceClassPolicyLog = "bookSourceClassPolicyLog" // P0-S4 类导入观察日志开关
    const val sourceRecycleBinEnabled = "sourceRecycleBinEnabled"
    const val processText = "process_text"
    const val cleanCache = "cleanCache"
    const val saveTabPosition = "saveTabPosition"
    const val fontFolder = "fontFolder"
    const val backupPath = "backupUri"
    const val restoreIgnore = "restoreIgnore"
    const val threadCount = "threadCount"
    // 线程池拆分：搜索类独立线程池 + 更新+缓存类独立线程池
    const val searchThreadCount = "searchThreadCount"
    const val updateCacheThreadCount = "updateCacheThreadCount"
    // B12 缓存并发率（格式同书源：纯数字=间隔毫秒 / 次数/毫秒）
    const val cacheConcurrentRate = "cacheConcurrentRate"
    // B16 批注导出 Obsidian（0=API/1=本地文件）
    const val obsidianExportMethod = "obsidianExportMethod"
    const val obsidianApiUrl = "obsidianApiUrl"
    const val obsidianApiKey = "obsidianApiKey"
    const val obsidianVaultSubPath = "obsidianVaultSubPath"
    const val obsidianLocalDirUri = "obsidianLocalDirUri"
    const val obsidianAutoExport = "obsidianAutoExport"
    // precise-manage: 网址记录开关（默认开启）
    const val recordUrl = "recordUrl"
    // precise-manage: 下载管理已隐藏任务 id（用户清除已完成但保留文件的记录）
    const val downloadDismissedIds = "downloadDismissedIds"
    const val migratedThreadCount = "migratedThreadCount" // 老用户迁移标志位（boolean）
    const val rssParseConcurrency = "rssParseConcurrency"
    const val imageLoadConcurrency = "imageLoadConcurrency"
    const val webPort = "webPort"
    const val keepLight = "keep_light"
    const val webService = "webService"
    const val webDavUrl = "web_dav_url"
    const val webDavAccount = "web_dav_account"
    const val webDavPassword = "web_dav_password"
    const val webDavDir = "webDavDir"
    const val cloudStorageType = "cloudStorageType"
    const val s3Endpoint = "s3Endpoint"
    const val s3Region = "s3Region"
    const val s3Bucket = "s3Bucket"
    const val s3Prefix = "s3Prefix"
    const val s3AccessKey = "s3AccessKey"
    const val s3SecretKey = "s3SecretKey"
    const val s3SessionToken = "s3SessionToken"
    const val s3PathStyle = "s3PathStyle"
    const val s3Containers = "s3Containers"
    const val s3ContainerSelections = "s3ContainerSelections"
    const val autoSwitchS3Container = "autoSwitchS3Container"
    const val s3FullWebDavFallbackNeverRemind = "s3FullWebDavFallbackNeverRemind"
    const val paragraphBubblePackage = "paragraphBubblePackage"
    const val autoRefreshMediaToc = "autoRefreshMediaToc"
    const val enableCustomExport = "enableCustomExport"
    const val exportToWebDav = "webDavCacheBackup"
    const val exportNoChapterName = "exportNoChapterName"
    const val exportType = "exportType"
    const val exportPictureFile = "exportPictureFile"
    const val changeSourceCheckAuthor = "changeSourceCheckAuthor"
    const val changeSourceLoadToc = "changeSourceLoadToc"
    const val changeSourceLoadInfo = "changeSourceLoadInfo"
    const val changeSourceLoadWordCount = "changeSourceLoadWordCount"
    const val chineseConverterType = "chineseConverterType"
    const val textSelectAble = "selectText"
    const val shareLayout = "shareLayout"
    const val comicStyleSelect = "comicStyleSelect"
    const val readStyleSelect = "readStyleSelect"
    const val systemTypefaces = "system_typefaces"
    const val readBodyToLh = "readBodyToLh"
    const val textFullJustify = "textFullJustify"
    const val textBottomJustify = "textBottomJustify"
    const val adaptSpecialStyle = "adaptSpecialStyle"
    const val autoReadSpeed = "autoReadSpeed"
    const val autoReadMode = "autoReadMode"
    const val readAloudFloatingBallSide = "readAloudFloatingBallSide"
    const val readAloudFloatingBallYPercent = "readAloudFloatingBallYPercent"
    const val libraryS3Containers = "libraryS3Containers"
    const val libraryS3ContainerSelections = "libraryS3ContainerSelections"
    const val contentSelectActions = "contentSelectActions"
    const val contentSelectMenuConfig = "contentSelectMenuConfig"
    const val contentSelectDefaultOpen = "contentSelectDefaultOpen"
    const val contentSelectSearchEngines = "contentSelectSearchEngines"
    const val contentSelectSearchEngineId = "contentSelectSearchEngineId"
    const val readMenuButtonLayout = "readMenuButtonLayout"
    const val barElevation = "barElevation"
    const val launcherIcon = "launcherIcon"
    const val transparentStatusBar = "transparentStatusBar"
    const val immNavigationBar = "immNavigationBar"
    const val defaultCover = "defaultCover"
    const val defaultCoverDark = "defaultCoverDark"
    const val replaceEnableDefault = "replaceEnableDefault"
    const val showBrightnessView = "showBrightnessView"
    const val autoClearExpired = "autoClearExpired"
    const val autoChangeSource = "autoChangeSource"
    const val importKeepName = "importKeepName"
    const val importKeepGroup = "importKeepGroup"
    const val screenOrientation = "screenOrientation"
    const val syncBookProgress = "syncBookProgress"
    const val syncBookProgressPlus = "syncBookProgressPlus"
    const val cronet = "Cronet"
    const val antiAlias = "antiAlias"
    const val bitmapCacheSize = "bitmapCacheSize"
    const val imageRetainNum = "imageRetainNum"
    const val preDownloadNum = "preDownloadNum"
    const val mangaPreDownloadNum = "mangaPreDownloadNum"
    const val mangaAutoPageSpeed = "mangaAutoPageSpeed"
    const val mangaFooterConfig = "mangaFooterConfig"
    const val disableClickScroll = "disableClickScroll"
    const val enableMangaHorizontalScroll = "enableMangaHorizontalScroll"
    const val hideMangaTitle = "hideMangaTitle"
    const val mangaColorFilter = "mangaColorFilter"
    const val enableMangaEInk = "enableMangaEInk"
    const val mangaEInkThreshold = "mangaEInkThreshold"
    const val disableHorizontalPageSnap = "disableHorizontalPageSnap"
    const val enableMangaGray = "enableMangaGray"
    const val autoRefresh = "auto_refresh"
    // F-P1-1 自动任务服务开关
    const val autoTaskService = "autoTaskService"
    // F-P1-3 调试日志悬浮球开关
    const val debugLogFloatingBall = "debugLogFloatingBall"
    const val onlyUpdateRead = "onlyUpdateRead"
    const val defaultToRead = "defaultToRead"
    const val exportCharset = "exportCharset"
    const val exportUseReplace = "exportUseReplace"
    const val useZhLayout = "useZhLayout"
    const val brightness = "brightness"
    const val nightBrightness = "nightBrightness"
    const val expandTextMenu = "expandTextMenu"
    const val doublePageHorizontal = "doubleHorizontalPage"
    const val readUrlOpenInBrowser = "readUrlInBrowser"
    const val defaultBookTreeUri = "defaultBookTreeUri"
    const val checkSource = "checkSource"
    const val uploadRule = "uploadRule"
    const val tocUiUseReplace = "tocUiUseReplace"
    const val tocCountWords = "tocCountWords"
    const val enableReadRecord = "enableReadRecord"
    const val localBookImportSort = "localBookImportSort"
    const val customWelcome = "customWelcome"
    const val welcomeShowTime = "welcomeShowTime"
    const val welcomeImage = "welcomeImagePath"
    const val welcomeImageDark = "welcomeImagePathDark"
    const val welcomeShowText = "welcomeShowText"
    const val welcomeShowTextDark = "welcomeShowTextDark"
    const val welcomeShowIcon = "welcomeShowIcon"
    const val welcomeShowIconDark = "welcomeShowIconDark"
    const val pageTouchSlop = "pageTouchSlop"
    const val pageTouchClick = "pageTouchClick"
    const val showAddToShelfAlert = "showAddToShelfAlert"
    const val ignoreAudioFocus = "ignoreAudioFocus"
    const val parallelExportBook = "parallelExportBook"
    const val progressBarBehavior = "progressBarBehavior"
    const val sourceEditMaxLine = "sourceEditMaxLine"
    const val ttsTimer = "ttsTimer"
    const val ttsTimerMode = "ttsTimerMode"
    const val ttsTimerChapters = "ttsTimerChapters"
    const val ttsParagraphPauseMs = "ttsParagraphPauseMs"
    const val pullDownBookmark = "pullDownBookmark"
    const val noAnimScrollPage = "noAnimScrollPage"
    const val webDavDeviceName = "webDavDeviceName"
    const val webServiceWakeLock = "webServiceWakeLock"
    const val audioPlayWakeLock = "audioPlayWakeLock"
    const val readAloudWakeLock = "readAloudWakeLock"
    const val showLastUpdateTime = "showLastUpdateTime"
    const val showWaitUpCount = "showWaitUpCount"
    const val clearWebViewData = "clearWebViewData"
    const val onlyLatestBackup = "onlyLatestBackup"
    const val brightnessVwPos = "brightnessVwPos"
    const val shrinkDatabase = "shrinkDatabase"
    const val batchChangeSourceDelay = "batchChangeSourceDelay"
    const val openBookInfoByClickTitle = "openBookInfoByClickTitle"
    const val defaultHomePage = "defaultHomePage"
    const val showBookshelfFastScroller = "showBookshelfFastScroller"
    const val importKeepEnable = "importKeepEnable"
    const val importShowComment = "importShowComment"
    const val clickImgWay = "clickImgWay"
    const val keyPageOnLongPress = "keyPageOnLongPress"
    const val volumeKeyPage = "volumeKeyPage"
    const val volumeKeyPageOnPlay = "volumeKeyPageOnPlay"
    const val mouseWheelPage = "mouseWheelPage"
    const val recordHeapDump = "recordHeapDump"
    const val optimizeRender = "optimizeRender"
    const val updateToVariant = "updateToVariant"
    const val streamReadAloudAudio = "streamReadAloudAudio"
    const val pauseReadAloudWhilePhoneCalls = "pauseReadAloudWhilePhoneCalls"
    const val readAloudByMediaButton = "readAloudByMediaButton"
    const val showMangaUi = "showMangaUi"
    const val disableMangaScale = "disableMangaScale"
    const val disableMangaPageAnim = "disableMangaPageAnim"
    const val paddingDisplayCutouts = "paddingDisplayCutouts"
    const val autoCheckNewBackup = "autoCheckNewBackup"

    const val dThemeName = "durThemeName"
    const val dNThemeName = "durThemeNameNight"

    const val cPrimary = "colorPrimary"
    const val cAccent = "colorAccent"
    const val cBackground = "colorBackground"
    const val cBBackground = "colorBottomBackground"
    const val bgImage = "backgroundImage"
    const val bgImageBlurring = "backgroundImageBlurring"
    const val tNavBar = "transparentNavBar"

    const val cNPrimary = "colorPrimaryNight"
    const val cNAccent = "colorAccentNight"
    const val cNBackground = "colorBackgroundNight"
    const val cNBBackground = "colorBottomBackgroundNight"
    const val bgImageN = "backgroundImageNight"
    const val bgImageNBlurring = "backgroundImageNightBlurring"
    const val tNavBarN = "transparentNavBarNight"

    const val showReadTitleAddition = "showReadTitleAddition"
    const val readBarStyleFollowPage = "readBarStyleFollowPage"
    const val contentSelectSpeakMod = "contentReadAloudMod"
    const val editFontScale = "editFontScale"
    const val editNonPrintable = "editNonPrintable"
    const val editAutoWrap = "editAutoWrap"
    const val editAutoComplete = "editAutoComplete"
    const val showBoardLine = "showBoardLine"

    // F-P0-2 备份选择器（借鉴蛋蛋Max）高亮规则相关 keys
    const val highlightRuleDialog = "highlightRuleDialog"
    const val highlightRuleBookTitle = "highlightRuleBookTitle"
    const val highlightRuleBracketNote = "highlightRuleBracketNote"
    const val highlightRuleItems = "highlightRuleItems"
    const val highlightRuleGroups = "highlightRuleGroups"
    const val highlightRuleCurrentGroup = "highlightRuleCurrentGroup"
    // T-B2: 覆盖安装一次性内置规则补齐标志（首次升级到 V2 时自动 MERGE 缺失 builtinIds）
    const val highlightRuleBuiltinMergedV2 = "highlightRuleBuiltinMergedV2"

    // F-P1-8 书源/订阅源文件夹视图模式（0=列表视图, 1=文件夹视图）—— 已废弃，保留兼容
    // （theme-rss-header-layout-sync F4: 原 rssViewMode 0 引用已删除；sourceViewMode 仍被
    //   AppConfig.migrateSourceConfigIfNeeded 迁移链引用，删除会破坏老用户数据迁移，保留）
    const val sourceViewMode = "sourceViewMode"
    // F-P6 文件夹视图配置（分组样式/间距）—— 已废弃，保留兼容
    const val sourceFolderStyle = "sourceFolderStyle"
    const val sourceFolderMargin = "sourceFolderMargin"

    // 书源/订阅源布局深度重构配置（学习书架两维度独立架构）
    const val sourceGroupStyle = "sourceGroupStyle"       // 0=列表, 1=按类型, 2=按分组
    const val sourceGroupMode = "sourceGroupMode"         // D1: 0=标签(Tab平铺), 1=分组(文件夹) —— 样式维度
    const val sourceLayout = "sourceLayout"               // 0=列表, 1=紧凑, 2-6=网格2-6列
    // C-01 修复：拆分为 bookSourceSort（书源专用）+ rssSort（订阅源专用），原 sourceSort 保留兼容读取
    const val bookSourceSort = "bookSourceSort"           // 书源排序：0=手动, 1=名称, 2=启用, 3=类型, 4=分组, 5=URL, 6=更新时间
    @Deprecated("C-01 修复：改用 bookSourceSort（书源）或 rssSort（订阅源），此 key 仅保留迁移兼容读取")
    const val sourceSort = "sourceSort"                   // 旧共享排序 key（迁移兼容）
    const val sourceMargin = "sourceMargin"               // 卡片间距 0-60
    const val sourceConfigMigrated = "sourceConfigMigrated"  // 迁移标志（布尔）
    // 订阅源排序（C-01 启用，原为死代码 C-05）：0=手动/1=名称/2=启用/3=类型/4=分组/5=URL/6=更新时间（与 bookSourceSort 语义统一）
    const val rssSort = "rssSort"
    const val rssSortAscending = "rssSortAscending"
    // M2 SourceContentFilter：BookSource 视频源 WebView 资源过滤（借鉴 RssSource contentWhitelist/contentBlacklist 机制）
    const val bookSourceContentBlacklist = "bookSourceContentBlacklist"
    const val bookSourceContentWhitelist = "bookSourceContentWhitelist"
    // M3 SourceCacheManager：BookSource 视频源 WebView 缓存策略（借鉴 RssSource cacheFirst 机制）
    const val bookSourceCacheFirst = "bookSourceCacheFirst"
    // M5 SourceWebViewController：BookSource 视频源 WebView JS 注入（借鉴 RssSource injectJs 机制）
    const val bookSourceInjectJs = "bookSourceInjectJs"
    // 阅读记录小组件（archive ReadRecordWidgetStore 依赖）
    const val readRecordRecentSnapshots = "readRecordRecentSnapshots"
    const val readRecordGoalConfig = "readRecordGoalConfig"
    const val readRecordComponents = "readRecordComponents"

    // ===== ui-redesign-m3 主题扩展（P1E：主题架构 v2 相关常量，增量合并不覆盖已有）=====
    // 字体（日夜拆分）
    const val fontScaleN = "fontScaleNight"
    const val uiFontPath = "ui_font_path"
    const val uiFontPathN = "ui_font_path_night"
    const val titleFontPath = "title_font_path"
    const val titleFontPathN = "title_font_path_night"
    const val uiFontColor = "ui_font_color"
    const val uiFontColorN = "ui_font_color_night"
    const val titleFontColor = "title_font_color"
    const val titleFontColorN = "title_font_color_night"
    const val bookCoverShadow = "bookCoverShadow"
    // 圆角/透明度/底色扩展（日夜拆分）
    const val uiCornerScale = "uiCornerScale"
    const val uiCornerScaleN = "uiCornerScaleNight"
    const val uiCornerEffectMode = "uiCornerEffectMode"
    const val uiCornerEffectLevel = "uiCornerEffectLevel"
    const val uiLayoutAlpha = "uiLayoutAlpha"
    const val uiLayoutAlphaN = "uiLayoutAlphaNight"
    const val dialogAlpha = "dialogAlpha"
    const val dialogAlphaN = "dialogAlphaNight"
    const val uiCornerSearchFollow = "uiCornerSearchFollow"
    const val uiCornerSearchFollowN = "uiCornerSearchFollowNight"
    const val uiCornerReplyFollow = "uiCornerReplyFollow"
    const val uiCornerReplyFollowN = "uiCornerReplyFollowNight"
    const val themeCardColor = "themeCardColor"
    const val themeCardColorN = "themeCardColorNight"
    const val themeMutedColor = "themeMutedColor"
    const val themeMutedColorN = "themeMutedColorNight"
    const val themeSearchFieldBackgroundColor = "themeSearchFieldBackgroundColor"
    const val themeSearchFieldBackgroundColorN = "themeSearchFieldBackgroundColorNight"
    const val themeTabBackgroundColor = "themeTabBackgroundColor"
    const val themeTabBackgroundColorN = "themeTabBackgroundColorNight"
    const val themeShelfColor = "themeShelfColor"
    const val themeShelfColorN = "themeShelfColorNight"
    const val themeCardShadow = "themeCardShadow"
    const val themeCardShadowN = "themeCardShadowNight"
    const val themeCardBackgroundBlur = "themeCardBackgroundBlur"
    const val themeCardBackgroundBlurN = "themeCardBackgroundBlurNight"
    // 主题背景图扩展
    const val bgImageCrop = "backgroundImageCrop"
    const val bgImageNCrop = "backgroundImageNightCrop"
    const val bookInfoBgImage = "bookInfoBackgroundImage"
    const val bookInfoBgImageN = "bookInfoBackgroundImageNight"
    const val panelBgImage = "panelBackgroundImage"
    const val panelBgImageN = "panelBackgroundImageNight"
    const val panelBgScaleType = "panelBackgroundScaleType"
    const val panelBgScaleTypeN = "panelBackgroundScaleTypeNight"
    const val panelBorderColor = "panelBorderColor"
    const val panelBorderColorN = "panelBorderColorNight"
    const val panelBorderAlpha = "panelBorderAlpha"
    const val panelBorderAlphaN = "panelBorderAlphaNight"
    // 高级标题（AdvancedTitle）
    const val advancedTitleConfig = "advancedTitleConfig"
    const val advancedTitleLottieJson = "advancedTitleLottieJson"
    const val advancedTitleLottiePath = "advancedTitleLottiePath"
    const val advancedTitleHeightFactor = "advancedTitleHeightFactor"
    const val advancedTitlePackage = "advancedTitlePackage"
    // ===== ui-redesign-m3 布局/外观套件（P1E：config 新类依赖，对齐 archive）=====
    const val mainLayoutPreset = "mainLayoutPreset"
    const val currentAppearanceKitId = "currentAppearanceKitId"
    const val defaultTopBarStyle = "defaultTopBarStyle"
    const val defaultTopBarShowSearch = "defaultTopBarShowSearch"
    const val floatingBottomBarHideSearch = "floatingBottomBarHideSearch"
    const val navigationBarPackageDay = "navigationBarPackageDay"
    const val navigationBarPackageNight = "navigationBarPackageNight"
    const val topBarPackageDay = "topBarPackageDay"
    const val topBarPackageNight = "topBarPackageNight"
    const val bottomBarLayoutMode = "bottomBarLayoutMode"
    const val bottomBarSidebarGravity = "bottomBarSidebarGravity"
    const val bottomBarEffectMode = "bottomBarEffectMode"
    const val liquidGlassLevel = "liquidGlassLevel"
    const val frostedGlassLevel = "frostedGlassLevel"
    const val themePackageSyncTasks = "themePackageSyncTasks"
    // 封面收藏（CoverCollection）
    const val coverCollectionDay = "coverCollectionDay"
    const val coverCollectionNight = "coverCollectionNight"
    const val coverCollectionModeDay = "coverCollectionModeDay"
    const val coverCollectionModeNight = "coverCollectionModeNight"
    // 书籍详情页组件/样式
    const val bookInfoComponents = "bookInfoComponents"
    const val bookInfoPageStyle = "bookInfoPageStyle"
    // 主题资源目录名
    const val dThemeDirName = "durThemeDirName"
    const val dNThemeDirName = "durThemeDirNameNight"

    // ===== archive-ui P1-F：AI 助手 + discovery 发现页配置常量（增量合并不覆盖已有）=====
    // discovery 发现页（AiSettingsTool / modernDiscovery 依赖）
    const val discoverySuiteConfig = "discoverySuiteConfig"
    const val selectedDiscoverySuiteId = "selectedDiscoverySuiteId"
    const val modernRssPage = "modernRssPage"
    const val discoveryPageLayout = "discoveryPageLayout"
    const val mergedDiscoveryRssTarget = "mergedDiscoveryRssTarget"
    const val modernDiscoverySourceUrl = "modernDiscoverySourceUrl"
    const val modernDiscoveryTagUrls = "modernDiscoveryTagUrls"
    const val modernRssSourceUrl = "modernRssSourceUrl"
    const val discoveryPageMode = "discoveryPageMode"
    const val modernDiscoveryPage = "modernDiscoveryPage"
    // AI 助手
    const val aiAssistantEnabled = "aiAssistantEnabled"
    const val aiProviderList = "aiProviderList"
    const val aiCurrentProviderId = "aiCurrentProviderId"
    const val aiModelConfigList = "aiModelConfigList"
    const val aiCurrentModelId = "aiCurrentModelId"
    const val aiAskModelId = "aiAskModelId"
    const val aiSummaryModelId = "aiSummaryModelId"
    const val aiReadAloudRoleModelId = "aiReadAloudRoleModelId"
    const val aiReadAloudRoleBackupModelId = "aiReadAloudRoleBackupModelId"
    const val aiReadAloudRoleFirstResponseTimeoutSeconds = "aiReadAloudRoleFirstResponseTimeoutSeconds"
    const val aiReadAloudAudioModelId = "aiReadAloudAudioModelId"
    const val aiReadAloudAudioBackupModelId = "aiReadAloudAudioBackupModelId"
    const val aiMcpServerList = "aiMcpServerList"
    const val aiChatSessionList = "aiChatSessionList"
    const val aiReadHistoryList = "aiReadHistoryList"
    const val aiCurrentChatSessionId = "aiCurrentChatSessionId"
    const val aiChatCompanionList = "aiChatCompanionList"
    const val aiCurrentChatCompanionId = "aiCurrentChatCompanionId"
    const val aiChatAutoSpeakEnabled = "aiChatAutoSpeakEnabled"
    const val aiThinkingToolbarEnabled = "aiThinkingToolbarEnabled"
    const val aiSystemPrompt = "aiSystemPrompt"
    const val aiSkillPrompt = "aiSkillPrompt"
    const val aiSkillList = "aiSkillList"
    const val aiWorldBookList = "aiWorldBookList"
    const val aiPersonaList = "aiPersonaList"
    const val aiCurrentPersonaId = "aiCurrentPersonaId"
    const val aiImageProviderList = "aiImageProviderList"
    const val aiCurrentImageProviderId = "aiCurrentImageProviderId"
    const val aiReadAloudRoleEnabled = "aiReadAloudRoleEnabled"
    const val aiReadAloudRoleThreadCount = "aiReadAloudRoleThreadCount"
    const val aiReadAloudRoleContextParagraphs = "aiReadAloudRoleContextParagraphs"
    const val aiReadAloudRoleMergeGapParagraphs = "aiReadAloudRoleMergeGapParagraphs"
    const val aiReadAloudRolePrompt = "aiReadAloudRolePrompt"
    const val aiReadAloudRoleMode = "aiReadAloudRoleMode"
    const val aiReadAloudRolePreprocess = "aiReadAloudRolePreprocess"
    const val aiReadAloudRolePreprocessRules = "aiReadAloudRolePreprocessRules"
    const val aiReadAloudBgmEnabled = "aiReadAloudBgmEnabled"
    const val aiReadAloudBgmPrompt = "aiReadAloudBgmPrompt"
    const val aiReadAloudSoundEffectPrompt = "aiReadAloudSoundEffectPrompt"
    const val aiReadAloudBgmVolume = "aiReadAloudBgmVolume"
    const val aiReadAloudSfxVolume = "aiReadAloudSfxVolume"
    const val readAloudSpeakerLoudnessEnabled = "readAloudSpeakerLoudnessEnabled"
    const val readAloudTargetVoiceVolume = "readAloudTargetVoiceVolume"
    const val readAloudMaxSpeakerGain = "readAloudMaxSpeakerGain"
    const val readAloudNarratorBaseGain = "readAloudNarratorBaseGain"
    const val readAloudSpeakerLoudnessStats = "readAloudSpeakerLoudnessStats"
    const val aiReadAloudAutoCreateCharacters = "aiReadAloudAutoCreateCharacters"
    const val aiReadAloudAutoCreateCharacterPrompt = "aiReadAloudAutoCreateCharacterPrompt"
    const val aiReadAloudAutoCreateAvatar = "aiReadAloudAutoCreateAvatar"
    const val aiContextCompressionEnabled = "aiContextCompressionEnabled"
    const val aiContextWindowTokens = "aiContextWindowTokens"
    const val aiThinkingContextTokens = "aiThinkingContextTokens"
    const val aiEnterToSend = "aiEnterToSend"
    const val aiChatAgentMode = "aiChatAgentMode"
    const val aiEnabledToolNames = "aiEnabledToolNames"
    const val aiEnabledToolNamesVersion = "aiEnabledToolNamesVersion"
    const val aiReadToolMode = "aiReadToolMode"
    const val aiAgentMaxToolRounds = "aiAgentMaxToolRounds"
    const val aiAgentToolMaxAttempts = "aiAgentToolMaxAttempts"
    const val aiAgentToolRetryBackoffMillis = "aiAgentToolRetryBackoffMillis"
    const val aiTavilyEnabled = "aiTavilyEnabled"
    const val aiTavilyApiKey = "aiTavilyApiKey"
    const val aiTavilyBaseUrl = "aiTavilyBaseUrl"
    const val aiTavilySearchDepth = "aiTavilySearchDepth"
    const val aiTavilyTopic = "aiTavilyTopic"
    const val aiTavilyMaxResults = "aiTavilyMaxResults"
    const val aiFloatingBallSide = "aiFloatingBallSide"
    const val aiFloatingBallYPercent = "aiFloatingBallYPercent"
    // ===== archive-ui P1-F：archive AppConfig 依赖的 PreferKey 常量（合并时补入本文件） =====
    const val aiBaseUrl = "aiBaseUrl"
    const val aiApiKey = "aiApiKey"
    const val aiCurrentModel = "aiCurrentModel"
    const val aiModelList = "aiModelList"
    const val bookshelfListItemStyle = "bookshelfListItemStyle"
    const val bookshelfListIntroLines = "bookshelfListIntroLines"
    const val bookshelfHiddenTags = "bookshelfHiddenTags"
    const val bookshelfGroupTags = "bookshelfGroupTags"
    const val bookshelfReturnToTopAfterRead = "bookshelfReturnToTopAfterRead"
    const val loadCoverHighQuality = "loadCoverHighQuality"
    const val showReadAloudFloatingBall = "showReadAloudFloatingBall"
    const val readAloudFloatingFontSize = "readAloudFloatingFontSize"
    const val readAloudFloatingBackgroundAlpha = "readAloudFloatingBackgroundAlpha"
    const val readAloudFloatingHeightPercent = "readAloudFloatingHeightPercent"
    const val forceSoftwareParagraphBubble = "forceSoftwareParagraphBubble"
    const val syncThemePackages = "syncThemePackages"
    const val mainTransparentStatusBar = "mainTransparentStatusBar"
    const val immersiveManageBar = "immersiveManageBar"
    const val highBrush = "highBrush"
    const val epubReadEngine = "epubReadEngine"
    const val epubCoreScheduleMode = "epubCoreScheduleMode"
    const val fastScrollerTouchTargetDp = "fastScrollerTouchTargetDp"
    const val readMenuAlpha = "readMenuAlpha"
    // 管理页背景透明度（ui-theme-governance-polish P6）：单 key 不分日夜（管理页日夜同源背景，
    // 显式决策非静默偏离 dialogAlpha 的分 key 范式），get/set 双向 coerceIn(0,100)
    const val manageBgAlpha = "manageBgAlpha"
}
